version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        networks:
            - app-network

    frontend:
        build:
            context: .
            dockerfile: web/Dockerfile
        ports:
            - '80:80'
        depends_on:
            - backend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
